environment: uat
account:
  logical_name: UAT

projects:
  health:
    code: HEALTH
    repository: enterprise-snowflake-health-analytics
  transport:
    code: TRANSPORT
    repository: enterprise-snowflake-transport-analytics

analytics_databases:
  health_uat:
    name: UAT_HEALTH
    project_code: HEALTH
    retention_days: 1
    schemas:
      - STAGING
      - INTERMEDIATE
      - CANONICAL
      - MARTS
      - SEMANTIC
  transport_uat:
    name: UAT_TRANSPORT
    project_code: TRANSPORT
    retention_days: 1
    schemas:
      - STAGING
      - INTERMEDIATE
      - CANONICAL
      - MARTS
      - SEMANTIC

platform_control:
  name: PLATFORM_CONTROL
  retention_days: 1
  schemas:
    - DEPLOYMENT
    - QUALITY
    - OBSERVABILITY
    - OPERATIONS

warehouses:
  health_uat:
    name: WH_HEALTH_UAT
    size: XSMALL
    auto_suspend_seconds: 60
    statement_timeout_seconds: 3600
  transport_uat:
    name: WH_TRANSPORT_UAT
    size: XSMALL
    auto_suspend_seconds: 60
    statement_timeout_seconds: 3600
  platform_ops:
    name: WH_PLATFORM_OPS
    size: XSMALL
    auto_suspend_seconds: 60
    statement_timeout_seconds: 3600
