environment: uat
account:
  logical_name: UAT

terraform_identity:
  user_name: SU_GITHUB_TERRAFORM_UAT
  role_name: AR_TERRAFORM_UAT
  github_environment: uat
  oidc_issuer: https://token.actions.githubusercontent.com
  oidc_subject: repo:ruizengalways/enterprise-snowflake-platform-infra:environment:uat

project_deploy_identity:
  github_owner: ruizengalways
  github_environment: uat
  oidc_issuer: https://token.actions.githubusercontent.com

projects:
  health:
    code: HEALTH
    repository: enterprise-snowflake-health-analytics
    warehouse_keys:
      query: health_query
      transform: health_transform
  transport:
    code: TRANSPORT
    repository: enterprise-snowflake-transport-analytics
    warehouse_keys:
      query: transport_query
      transform: transport_transform

analytics_databases:
  health_uat:
    name: UAT_HEALTH
    project_code: HEALTH
    retention_days: 1
    schemas:
      - STAGING
      - INTERMEDIATE
      - CANONICAL
      - MARTS
      - SEMANTIC
    published_schemas:
      - MARTS
      - SEMANTIC
  transport_uat:
    name: UAT_TRANSPORT
    project_code: TRANSPORT
    retention_days: 1
    schemas:
      - STAGING
      - INTERMEDIATE
      - CANONICAL
      - MARTS
      - SEMANTIC
    published_schemas:
      - MARTS
      - SEMANTIC

platform_control:
  name: PLATFORM_CONTROL
  retention_days: 1
  schemas:
    - DEPLOYMENT
    - QUALITY
    - OBSERVABILITY
    - OPERATIONS

warehouses:
  health_query:
    name: WH_HEALTH_QUERY
    size: XSMALL
    auto_suspend_seconds: 60
    statement_timeout_seconds: 3600
  health_transform:
    name: WH_HEALTH_TRANSFORM
    size: XSMALL
    auto_suspend_seconds: 60
    statement_timeout_seconds: 3600
  transport_query:
    name: WH_TRANSPORT_QUERY
    size: XSMALL
    auto_suspend_seconds: 60
    statement_timeout_seconds: 3600
  transport_transform:
    name: WH_TRANSPORT_TRANSFORM
    size: XSMALL
    auto_suspend_seconds: 60
    statement_timeout_seconds: 3600
  platform_ops:
    name: WH_PLATFORM_OPS
    size: XSMALL
    auto_suspend_seconds: 60
    statement_timeout_seconds: 3600
